# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run on commit

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write # This allows git push via GITHUB_TOKEN

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generates stats  
      run: |
        mkdir -p .repo_info
        python reporting_scripts/generate_stat_summary.py > .repo_info/stats.txt
        python reporting_scripts/generate_tsv_from_kb.py -o > .repo_info/objectives.txt
        python reporting_scripts/generate_tsv_from_kb.py -t > .repo_info/techniques.txt
        python reporting_scripts/generate_tsv_from_kb.py -t -l > .repo_info/techniques_long.txt
        python reporting_scripts/generate_tsv_from_kb.py -w > .repo_info/weaknesses.txt
        python reporting_scripts/generate_tsv_from_kb.py -w -l > .repo_info/weaknesses_long.txt
        python reporting_scripts/generate_tsv_from_kb.py -m > .repo_info/mitigations.txt
        python reporting_scripts/generate_tsv_from_kb.py -c > .repo_info/CASE_mapping.txt
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .repo_info/stats.txt
        git add .repo_info/objectives.txt
        git add .repo_info/techniques.txt
        git add .repo_info/techniques_long.txt
        git add .repo_info/weaknesses.txt
        git add .repo_info/weaknesses_long.txt
        git add .repo_info/mitigations.txt
        git add .repo_info/CASE_mapping.txt
        git commit -m "Update stats [skip ci]" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
